webtalk_init -webtalk_dir /home/holmes/Bureau/VHDL/VHDL_Ethernet/ethernet/ethernet.sim/sim_1/behav/xsim/xsim.dir/test_receiver_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 23 11:32:20 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "326d1f85-d985-4aae-86b9-37573b7944b3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0aa4fba5113d42ff9fb1f1adba077481" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "100" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "800.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "134.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1750 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "122616_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2811595884 -regid "" -xml /home/holmes/Bureau/VHDL/VHDL_Ethernet/ethernet/ethernet.sim/sim_1/behav/xsim/xsim.dir/test_receiver_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/holmes/Bureau/VHDL/VHDL_Ethernet/ethernet/ethernet.sim/sim_1/behav/xsim/xsim.dir/test_receiver_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/holmes/Bureau/VHDL/VHDL_Ethernet/ethernet/ethernet.sim/sim_1/behav/xsim/xsim.dir/test_receiver_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
